version: "3.4"

services:
  tinyified:
    container_name: tinyified
    image: tinyified:latest
    ports:
      - 5000:80
    env_file:
      - ./app/.env
    build:
      dockerfile: ./Dockerfile
    networks:
      - app

networks:
  app:

volumes:
  build:
