version: "3.4"

services:
  tinyified:
    container_name: tboi 
    image: tboi:latest
    ports:
      - 5001:80
    env_file:
      - ./app/.env
    build:
      dockerfile: ./Dockerfile.local
    networks:
      - app

networks:
  app:

volumes:
  build:
