use serde::{Serialize, Deserialize};

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct Character{
    pub id: i32,
    pub name: String,
    pub unlock_url: String,
    pub locked_url: String,
    pub character_unlock: i32,
    pub cross: i32,
    pub polaroid: i32,
    pub inverted_cross: i32,
    pub negative: i32,
    pub brimstone: i32,
    pub star: i32,
    pub hushs_face: i32,
    pub cent_sign: i32,
    pub wrinkled_paper: i32,
    pub knife: i32,
    pub dads_note: i32,
    pub hard_heart: i32,
    pub hard_cent_sign: i32,
    pub hard_hard_all: i32,
}

impl Character{
    pub fn new() -> Vec<Character>
    {
        let mut characters = Vec::new();

        characters.push(Character{
            id: 0,
            name: "Isaac".to_string(),
            character_unlock: -1,
            unlock_url: "isaac.png".to_string(),
            locked_url: "".to_string(),
            cross: 106,
            polaroid: 49,
            inverted_cross: 43,
            negative: 149,
            brimstone: 205,
            star: 70,
            hushs_face: 179,
            cent_sign: 192,
            wrinkled_paper: 282,
            knife: 440,
            dads_note: 441,
            hard_heart: 167,
            hard_cent_sign: 296,
            hard_hard_all: 253,
        });

        characters.push(Character{
            id: 1,
            name: "Magdalene".to_string(),
            unlock_url: "maggy.png".to_string(),
            locked_url: "maggy_locked.png".to_string(),
            character_unlock: 1,
            cross: 20,
            polaroid: 50,
            inverted_cross: 45,
            negative: 71,
            brimstone: 206,
            star: 109,
            hushs_face: 180,
            cent_sign: 193,
            wrinkled_paper: 283,
            knife: 442,
            dads_note: 443,
            hard_heart: 168,
            hard_cent_sign: 297,
            hard_hard_all: 254,
        });

        characters.push(Character{
            id: 2,
            name: "Cain".to_string(),
            unlock_url: "cain.png".to_string(),
            locked_url: "cain_locked.png".to_string(),
            character_unlock: 2,
            cross: 21,
            polaroid: 75,
            inverted_cross: 46,
            negative: 51,
            brimstone: 207,
            star: 110,
            hushs_face: 181,
            cent_sign: 194,
            wrinkled_paper: 284,
            knife: 444,
            dads_note: 445,
            hard_heart: 171,
            hard_cent_sign: 298,
            hard_hard_all: 261,
        });

        characters.push(Character{
            id: 3,
            name: "Judas".to_string(),
            unlock_url: "judas.png".to_string(),
            locked_url: "judas_locked.png".to_string(),
            character_unlock: 3,
            cross: 107,
            polaroid: 77,
            inverted_cross: 72,
            negative: 52,
            brimstone: 208,
            star: 108,
            hushs_face: 182,
            cent_sign: 195,
            wrinkled_paper: 285,
            knife: 446,
            dads_note: 447,
            hard_heart: 170,
            hard_cent_sign: 299,
            hard_hard_all: 263,
        });

        characters.push(Character{
            id: 4,
            name: "???".to_string(),
            unlock_url: "bluebaby.png".to_string(),
            locked_url: "bluebaby_locked.png".to_string(),
            character_unlock: 32,
            cross: 29,
            polaroid: 113,
            inverted_cross: 48,
            negative: 73,
            brimstone: 209,
            star: 114,
            hushs_face: 183,
            cent_sign: 196,
            wrinkled_paper: 286,
            knife: 448,
            dads_note: 449,
            hard_heart: 174,
            hard_cent_sign: 300,
            hard_hard_all: 252,
        });

        characters.push(Character{
            id: 5,
            name: "Eve".to_string(),
            unlock_url: "eve.png".to_string(),
            locked_url: "eve_locked.png".to_string(),
            character_unlock: 42,
            cross: 76,
            polaroid: 53,
            inverted_cross: 44,
            negative: 111,
            brimstone: 210,
            star: 112,
            hushs_face: 184,
            cent_sign: 197,
            wrinkled_paper: 288,
            knife: 450,
            dads_note: 451,
            hard_heart: 169,
            hard_cent_sign: 302,
            hard_hard_all: 255,
        });

        characters.push(Character{
            id: 6,
            name: "Samson".to_string(),
            unlock_url: "samson.png".to_string(),
            locked_url: "samson_locked.png".to_string(),
            character_unlock: 67,
            cross: 54,
            polaroid: 55,
            inverted_cross: 56,
            negative: 74,
            brimstone: 211,
            star: 115,
            hushs_face: 185,
            cent_sign: 198,
            wrinkled_paper: 287,
            knife: 452,
            dads_note: 453,
            hard_heart: 177,
            hard_cent_sign: 301,
            hard_hard_all: 262,
        });

        characters.push(Character{
            id: 7,
            name: "Azazel".to_string(),
            unlock_url: "azazel.png".to_string(),
            locked_url: "azazel_locked.png".to_string(),
            character_unlock: 79,
            cross: 126,
            polaroid: 128,
            inverted_cross: 127,
            negative: 47,
            brimstone: 212,
            star: 9,
            hushs_face: 186,
            cent_sign: 199,
            wrinkled_paper: 290,
            knife: 454,
            dads_note: 455,
            hard_heart: 173,
            hard_cent_sign: 304,
            hard_hard_all: 259,
        });

        characters.push(Character{
            id: 8,
            name: "Lazarus".to_string(),
            unlock_url: "lazarus.png".to_string(),
            locked_url: "lazarus_locked.png".to_string(),
            character_unlock: 80,
            cross: 116,
            polaroid: 118,
            inverted_cross: 117,
            negative: 119,
            brimstone: 213,
            star: 105,
            hushs_face: 187,
            cent_sign: 200,
            wrinkled_paper: 291,
            knife: 456,
            dads_note: 457,
            hard_heart: 172,
            hard_cent_sign: 305,
            hard_hard_all: 257,
        });

        characters.push(Character{
            id: 9,
            name: "Eden".to_string(),
            unlock_url: "eden.png".to_string(),
            locked_url: "eden_locked.png".to_string(),
            character_unlock: 81,
            cross: 121,
            polaroid: 123,
            inverted_cross: 122,
            negative: 124,
            brimstone: 214,
            star: 125,
            hushs_face: 188,
            cent_sign: 201,
            wrinkled_paper: 289,
            knife: 458,
            dads_note: 459,
            hard_heart: 176,
            hard_cent_sign: 303,
            hard_hard_all: 256,
        });

        characters.push(Character{
            id: 10,
            name: "The Lost".to_string(),
            unlock_url: "lost.png".to_string(),
            locked_url: "lost_locked.png".to_string(),
            character_unlock: 82,
            cross: 129,
            polaroid: 131,
            inverted_cross: 130,
            negative: 132,
            brimstone: 215,
            star: 133,
            hushs_face: 189,
            cent_sign: 202,
            wrinkled_paper: 293,
            knife: 460,
            dads_note: 461,
            hard_heart: 175,
            hard_cent_sign: 307,
            hard_hard_all: 156,
        });

        characters.push(Character{
            id: 11,
            name: "Lilith".to_string(),
            unlock_url: "lilith.png".to_string(),
            locked_url: "lilith_locked.png".to_string(),
            character_unlock: 199,
            cross: 218,
            polaroid: 219,
            inverted_cross: 220,
            negative: 221,
            brimstone: 216,
            star: 222,
            hushs_face: 190,
            cent_sign: 203,
            wrinkled_paper: 292,
            knife: 462,
            dads_note: 463,
            hard_heart: 223,
            hard_cent_sign: 306,
            hard_hard_all: 260,
        });

        characters.push(Character{
            id: 12,
            name: "Keeper".to_string(),
            unlock_url: "keeper.png".to_string(),
            locked_url: "keeper_locked.png".to_string(),
            character_unlock: 251,
            cross: 244,
            polaroid: 238,
            inverted_cross: 249,
            negative: 239,
            brimstone: 217,
            star: 240,
            hushs_face: 191,
            cent_sign: 204,
            wrinkled_paper: 294,
            knife: 464,
            dads_note: 465,
            hard_heart: 241,
            hard_cent_sign: 308,
            hard_hard_all: 264,
        });

        characters.push(Character{
            id: 13,
            name: "Apollyon".to_string(),
            unlock_url: "apollyon.png".to_string(),
            locked_url: "apollyon_locked.png".to_string(),
            character_unlock: 340,
            cross: 310,
            polaroid: 312,
            inverted_cross: 311,
            negative: 313,
            brimstone: 317,
            star: 314,
            hushs_face: 315,
            cent_sign: 316,
            wrinkled_paper: 295,
            knife: 466,
            dads_note: 467,
            hard_heart: 318,
            hard_cent_sign: 309,
            hard_hard_all: 319,
        });

        characters.push(Character{
            id: 14,
            name: "The Forgotten".to_string(),
            unlock_url: "forgotten.png".to_string(),
            locked_url: "forgotten_locked.png".to_string(),
            character_unlock: 390,
            cross: 393,
            polaroid: 395,
            inverted_cross: 394,
            negative: 396,
            brimstone: 403,
            star: 397,
            hushs_face: 398,
            cent_sign: 399,
            wrinkled_paper: 401,
            knife: 468,
            dads_note: 469,
            hard_heart: 392,
            hard_cent_sign: 400,
            hard_hard_all: 402,
        });

        characters.push(Character{
            id: 15,
            name: "Bethany".to_string(),
            unlock_url: "bethany.png".to_string(),
            locked_url: "bethany_locked.png".to_string(),
            character_unlock: 404,
            cross: 417,
            polaroid: 419,
            inverted_cross: 418,
            negative: 420,
            brimstone: 427,
            star: 421,
            hushs_face: 423,
            cent_sign: 422,
            wrinkled_paper: 425,
            knife: 470,
            dads_note: 471,
            hard_heart: 416,
            hard_cent_sign: 424,
            hard_hard_all: 426,
        });

        characters.push(Character{
            id: 16,
            name: "Jacob and Esau".to_string(),
            unlock_url: "jacob.png".to_string(),
            locked_url: "jacob_locked.png".to_string(),
            character_unlock: 405,
            cross: 429,
            polaroid: 431,
            inverted_cross: 430,
            negative: 432,
            brimstone: 439,
            star: 433,
            hushs_face: 435,
            cent_sign: 434,
            wrinkled_paper: 437,
            knife: 440,
            dads_note: 441,
            hard_heart: 428,
            hard_cent_sign: 436,
            hard_hard_all: 438,
        });

        characters.push(Character{
            id: 17,
            name: "T_Isaac".to_string(),
            unlock_url: "t_isaac.png".to_string(),
            locked_url: "t_isaac_locked.png".to_string(),
            character_unlock: 474,
            cross: 548,
            polaroid: 548,
            inverted_cross: 548,
            negative: 548,
            brimstone: 601,
            star: 618,
            hushs_face: 618,
            cent_sign: 541,
            wrinkled_paper: 584,
            knife: 549,
            dads_note: 491,
            hard_heart: -1,
            hard_cent_sign: -1,
            hard_hard_all: -1,
        });

        characters.push(Character{
            id: 18,
            name: "T_Magdalene".to_string(),
            unlock_url: "t_maggy.png".to_string(),
            locked_url: "t_maggy_locked.png".to_string(),
            character_unlock: 475,
            cross: 550,
            polaroid: 550,
            inverted_cross: 550,
            negative: 550,
            brimstone: 602,
            star: 619,
            hushs_face: 619,
            cent_sign: 530,
            wrinkled_paper: 585,
            knife: 551,
            dads_note: 492,
            hard_heart: -1,
            hard_cent_sign: -1,
            hard_hard_all: -1,
        });

        characters.push(Character{
            id: 19,
            name: "T_Cain".to_string(),
            unlock_url: "t_cain.png".to_string(),
            locked_url: "t_cain_locked.png".to_string(),
            character_unlock: 476,
            cross: 552,
            polaroid: 552,
            inverted_cross: 552,
            negative: 552,
            brimstone: 603,
            star: 620,
            hushs_face: 620,
            cent_sign: 534,
            wrinkled_paper: 586,
            knife: 553,
            dads_note: 493,
            hard_heart: -1,
            hard_cent_sign: -1,
            hard_hard_all: -1,
        });

        characters.push(Character{
            id: 20,
            name: "T_Judas".to_string(),
            unlock_url: "t_judas.png".to_string(),
            locked_url: "t_judas_locked.png".to_string(),
            character_unlock: 477,
            cross: 554,
            polaroid: 554,
            inverted_cross: 554,
            negative: 554,
            brimstone: 604,
            star: 621,
            hushs_face: 621,
            cent_sign: 525,
            wrinkled_paper: 587,
            knife: 555,
            dads_note: 494,
            hard_heart: -1,
            hard_cent_sign: -1,
            hard_hard_all: -1,
        });

        characters.push(Character{
            id: 21,
            name: "T_???".to_string(),
            unlock_url: "t_bluebaby.png".to_string(),
            locked_url: "t_bluebaby_locked.png".to_string(),
            character_unlock: 478,
            cross: 556,
            polaroid: 556,
            inverted_cross: 556,
            negative: 556,
            brimstone: 605,
            star: 622,
            hushs_face: 622,
            cent_sign: 528,
            wrinkled_paper: 588,
            knife: 557,
            dads_note: 495,
            hard_heart: -1,
            hard_cent_sign: -1,
            hard_hard_all: -1,
        });

        characters.push(Character{
            id: 22,
            name: "T_Eve".to_string(),
            unlock_url: "t_eve.png".to_string(),
            locked_url: "t_eve_locked.png".to_string(),
            character_unlock: 479,
            cross: 558,
            polaroid: 558,
            inverted_cross: 558,
            negative: 558,
            brimstone: 606,
            star: 623,
            hushs_face: 623,
            cent_sign: 527,
            wrinkled_paper: 589,
            knife: 559,
            dads_note: 496,
            hard_heart: -1,
            hard_cent_sign: -1,
            hard_hard_all: -1,
        });

        characters.push(Character{
            id: 23,
            name: "T_Samson".to_string(),
            unlock_url: "t_samson.png".to_string(),
            locked_url: "t_samson_locked.png".to_string(),
            character_unlock: 480,
            cross: 560,
            polaroid: 560,
            inverted_cross: 560,
            negative: 560,
            brimstone: 607,
            star: 624,
            hushs_face: 624,
            cent_sign: 535,
            wrinkled_paper: 590,
            knife: 561,
            dads_note: 497,
            hard_heart: -1,
            hard_cent_sign: -1,
            hard_hard_all: -1,
        });

        characters.push(Character{
            id: 24,
            name: "T_Azazel".to_string(),
            unlock_url: "t_azazel.png".to_string(),
            locked_url: "t_azazel_locked.png".to_string(),
            character_unlock: 481,
            cross: 562,
            polaroid: 562,
            inverted_cross: 562,
            negative: 562,
            brimstone: 608,
            star: 625,
            hushs_face: 625,
            cent_sign: 539,
            wrinkled_paper: 591,
            knife: 563,
            dads_note: 498,
            hard_heart: -1,
            hard_cent_sign: -1,
            hard_hard_all: -1,
        });

        characters.push(Character{
            id: 25,
            name: "T_Lazarus".to_string(),
            unlock_url: "t_lazarus.png".to_string(),
            locked_url: "t_lazarus_locked.png".to_string(),
            character_unlock: 482,
            cross: 564,
            polaroid: 564,
            inverted_cross: 564,
            negative: 564,
            brimstone: 609,
            star: 626,
            hushs_face: 626,
            cent_sign: 543,
            wrinkled_paper: 592,
            knife: 565,
            dads_note: 499,
            hard_heart: -1,
            hard_cent_sign: -1,
            hard_hard_all: -1,
        });

        characters.push(Character{
            id: 26,
            name: "T_Eden".to_string(),
            unlock_url: "t_eden.png".to_string(),
            locked_url: "t_eden_locked.png".to_string(),
            character_unlock: 483,
            cross: 566,
            polaroid: 566,
            inverted_cross: 566,
            negative: 566,
            brimstone: 610,
            star: 627,
            hushs_face: 627,
            cent_sign: 544,
            wrinkled_paper: 593,
            knife: 567,
            dads_note: 500,
            hard_heart: -1,
            hard_cent_sign: -1,
            hard_hard_all: -1,
        });

        characters.push(Character{
            id: 27,
            name: "T_The_Lost".to_string(),
            unlock_url: "t_lost.png".to_string(),
            locked_url: "t_lost_locked.png".to_string(),
            character_unlock: 484,
            cross: 568,
            polaroid: 568,
            inverted_cross: 568,
            negative: 568,
            brimstone: 611,
            star: 628,
            hushs_face: 628,
            cent_sign: 524,
            wrinkled_paper: 594,
            knife: 569,
            dads_note: 501,
            hard_heart: -1,
            hard_cent_sign: -1,
            hard_hard_all: -1,
        });

        characters.push(Character{
            id: 28,
            name: "T_Lilith".to_string(),
            unlock_url: "t_lilith.png".to_string(),
            locked_url: "t_lilith_locked.png".to_string(),
            character_unlock: 485,
            cross: 570,
            polaroid: 570,
            inverted_cross: 570,
            negative: 570,
            brimstone: 612,
            star: 629,
            hushs_face: 629,
            cent_sign: 526,
            wrinkled_paper: 595,
            knife: 571,
            dads_note: 502,
            hard_heart: -1,
            hard_cent_sign: -1,
            hard_hard_all: -1,
        });

        characters.push(Character{
            id: 29,
            name: "T_Keeper".to_string(),
            unlock_url: "t_keeper.png".to_string(),
            locked_url: "t_keeper_locked.png".to_string(),
            character_unlock: 486,
            cross: 572,
            polaroid: 572,
            inverted_cross: 572,
            negative: 572,
            brimstone: 613,
            star: 630,
            hushs_face: 630,
            cent_sign: 536,
            wrinkled_paper: 596,
            knife: 573,
            dads_note: 503,
            hard_heart: -1,
            hard_cent_sign: -1,
            hard_hard_all: -1,
        });

        characters.push(Character{
            id: 30,
            name: "T_Apollyon".to_string(),
            unlock_url: "t_apollyon.png".to_string(),
            locked_url: "t_apollyon_locked.png".to_string(),
            character_unlock: 487,
            cross: 574,
            polaroid: 574,
            inverted_cross: 574,
            negative: 574,
            brimstone: 614,
            star: 631,
            hushs_face: 631,
            cent_sign: 540,
            wrinkled_paper: 597,
            knife: 575,
            dads_note: 504,
            hard_heart: -1,
            hard_cent_sign: -1,
            hard_hard_all: -1,
        });

        characters.push(Character{
            id: 31,
            name: "T_The_Forgotten".to_string(),
            unlock_url: "t_forgotten.png".to_string(),
            locked_url: "t_forgotten_locked.png".to_string(),
            character_unlock: 488,
            cross: 576,
            polaroid: 576,
            inverted_cross: 576,
            negative: 576,
            brimstone: 615,
            star: 632,
            hushs_face: 632,
            cent_sign: 537,
            wrinkled_paper: 598,
            knife: 577,
            dads_note: 505,
            hard_heart: -1,
            hard_cent_sign: -1,
            hard_hard_all: -1,
        });

        characters.push(Character{
            id: 32,
            name: "T_Bethany".to_string(),
            unlock_url: "t_bethany.png".to_string(),
            locked_url: "t_bethany_locked.png".to_string(),
            character_unlock: 489,
            cross: 578,
            polaroid: 578,
            inverted_cross: 578,
            negative: 578,
            brimstone: 616,
            star: 633,
            hushs_face: 633,
            cent_sign: 529,
            wrinkled_paper: 599,
            knife: 579,
            dads_note: 506,
            hard_heart: -1,
            hard_cent_sign: -1,
            hard_hard_all: -1,
        });

        characters.push(Character{
            id: 33,
            name: "T_Jacob_and_Esau".to_string(),
            unlock_url: "t_jacob.png".to_string(),
            locked_url: "t_jacob_locked.png".to_string(),
            character_unlock: 490,
            cross: 580,
            polaroid: 580,
            inverted_cross: 580,
            negative: 580,
            brimstone: 617,
            star: 634,
            hushs_face: 634,
            cent_sign: 542,
            wrinkled_paper: 600,
            knife: 581,
            dads_note: 507,
            hard_heart: -1,
            hard_cent_sign: -1,
            hard_hard_all: -1,
        });

        return characters;
    }
}
